version: '3'
services:
  product-api:
    build:
      dockerfile: ./Docker/Dockerfile
      context: ./Product.AppServer
    ports:
      - "6080:8080"
  productwebui:
    build:
      dockerfile: ./Docker/Dockerfile
      context: ./Product.WebServer
    ports:
      - "9080:9080"
  